services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gym-app-backend
    working_dir: /var/www/gym-app-backend
    volumes:
      - .:/var/www/gym-app-backend
    depends_on:
      - db
      - redis
      - mailhog
    restart: unless-stopped
    networks:
      - gym-network
    entrypoint: >
      sh -c "chmod -R 777 /var/www/gym-app-backend/storage &&
             chmod -R 777 /var/www/gym-app-backend/bootstrap/cache &&
             chown -R gym_app_backend:gym_app_backend /var/www/gym-app-backend/storage &&
             chown -R gym_app_backend:gym_app_backend /var/www/gym-app-backend/bootstrap/cache &&
             php-fpm"

  nginx:
    image: nginx:latest
    container_name: gym-app-backend-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/gym-app-backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - gym-network

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gym-app-backend-queue
    command: php artisan queue:work --sleep=3 --tries=3
    working_dir: /var/www/gym-app-backend
    volumes:
      - .:/var/www/gym-app-backend
    depends_on:
      - app
      - db
    restart: unless-stopped
    networks:
      - gym-network

  db:
    image: postgres:15
    container_name: gym-app-backend-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - gym-network

  redis:
    image: redis:alpine
    container_name: gym-app-backend-redis
    ports:
      - "6378:6379"
    restart: unless-stopped
    networks:
      - gym-network

  mailhog:
    image: mailhog/mailhog
    container_name: gym_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge

volumes:
  pgdata:
